### ISSUE TITLE
gdscript 可以，GDScript 为什么不可以？

### ISSUE THREAD

**Issue by QuinnHu-star** [RobTheFiveNine/obsidian-gdscript#2]
如题

**Comment by RobTheFiveNine** [comment]
Hey @TheRiceBarn  thanks for reporting this. It looks like the library that Obsidian uses for syntax highlighting is case sensitive. I'll add a variation of the casing though to support using `GDScript` as well as `gdscript`.

嘿@TheRiceBarn，感谢您报告此问题。Obsidian 用于语法高亮的库似乎区分大小写。我将添加大小写变体以支持使用“GDScript”和“gdscript”。我不会说中文，所以我使用谷歌翻译来生成此内容。如果翻译得不好，我深表歉意。

**Comment by RobTheFiveNine** [comment]
This is included in the latest update (version 1.0.3). Thanks again.

这包含在最新更新（版本 1.0.3）中。再次感谢。
